-- Create device_catalog table for predefined device models
CREATE TABLE public.device_catalog (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  brand text NOT NULL,
  model text NOT NULL,
  device_type text NOT NULL DEFAULT 'HANDY',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE(brand, model)
);

-- Enable RLS
ALTER TABLE public.device_catalog ENABLE ROW LEVEL SECURITY;

-- Employees can view the catalog
CREATE POLICY "Employees can view device catalog" 
ON public.device_catalog 
FOR SELECT 
USING (is_employee(auth.uid()));

-- Admins can manage the catalog
CREATE POLICY "Admins can manage device catalog" 
ON public.device_catalog 
FOR ALL 
USING (has_role(auth.uid(), 'ADMIN'::app_role));

-- Insert Apple devices
INSERT INTO public.device_catalog (brand, model, device_type) VALUES
('Apple', 'iPhone 6', 'HANDY'),
('Apple', 'iPhone 6 Plus', 'HANDY'),
('Apple', 'iPhone 6s', 'HANDY'),
('Apple', 'iPhone 6s Plus', 'HANDY'),
('Apple', 'iPhone SE (2016)', 'HANDY'),
('Apple', 'iPhone 7', 'HANDY'),
('Apple', 'iPhone 7 Plus', 'HANDY'),
('Apple', 'iPhone 8', 'HANDY'),
('Apple', 'iPhone 8 Plus', 'HANDY'),
('Apple', 'iPhone X', 'HANDY'),
('Apple', 'iPhone XR', 'HANDY'),
('Apple', 'iPhone XS', 'HANDY'),
('Apple', 'iPhone XS Max', 'HANDY'),
('Apple', 'iPhone 11', 'HANDY'),
('Apple', 'iPhone 11 Pro', 'HANDY'),
('Apple', 'iPhone 11 Pro Max', 'HANDY'),
('Apple', 'iPhone SE (2020)', 'HANDY'),
('Apple', 'iPhone 12 mini', 'HANDY'),
('Apple', 'iPhone 12', 'HANDY'),
('Apple', 'iPhone 12 Pro', 'HANDY'),
('Apple', 'iPhone 12 Pro Max', 'HANDY'),
('Apple', 'iPhone 13 mini', 'HANDY'),
('Apple', 'iPhone 13', 'HANDY'),
('Apple', 'iPhone 13 Pro', 'HANDY'),
('Apple', 'iPhone 13 Pro Max', 'HANDY'),
('Apple', 'iPhone SE (2022)', 'HANDY'),
('Apple', 'iPhone 14', 'HANDY'),
('Apple', 'iPhone 14 Plus', 'HANDY'),
('Apple', 'iPhone 14 Pro', 'HANDY'),
('Apple', 'iPhone 14 Pro Max', 'HANDY'),
('Apple', 'iPhone 15', 'HANDY'),
('Apple', 'iPhone 15 Plus', 'HANDY'),
('Apple', 'iPhone 15 Pro', 'HANDY'),
('Apple', 'iPhone 15 Pro Max', 'HANDY'),
('Apple', 'iPhone 16', 'HANDY'),
('Apple', 'iPhone 16 Plus', 'HANDY'),
('Apple', 'iPhone 16 Pro', 'HANDY'),
('Apple', 'iPhone 16 Pro Max', 'HANDY'),
-- Samsung Galaxy S Series
('Samsung', 'Galaxy S7', 'HANDY'),
('Samsung', 'Galaxy S7 Edge', 'HANDY'),
('Samsung', 'Galaxy S8', 'HANDY'),
('Samsung', 'Galaxy S8+', 'HANDY'),
('Samsung', 'Galaxy S9', 'HANDY'),
('Samsung', 'Galaxy S9+', 'HANDY'),
('Samsung', 'Galaxy S10e', 'HANDY'),
('Samsung', 'Galaxy S10', 'HANDY'),
('Samsung', 'Galaxy S10+', 'HANDY'),
('Samsung', 'Galaxy S10 Lite', 'HANDY'),
('Samsung', 'Galaxy S20', 'HANDY'),
('Samsung', 'Galaxy S20+', 'HANDY'),
('Samsung', 'Galaxy S20 Ultra', 'HANDY'),
('Samsung', 'Galaxy S20 FE', 'HANDY'),
('Samsung', 'Galaxy S21', 'HANDY'),
('Samsung', 'Galaxy S21+', 'HANDY'),
('Samsung', 'Galaxy S21 Ultra', 'HANDY'),
('Samsung', 'Galaxy S21 FE', 'HANDY'),
('Samsung', 'Galaxy S22', 'HANDY'),
('Samsung', 'Galaxy S22+', 'HANDY'),
('Samsung', 'Galaxy S22 Ultra', 'HANDY'),
('Samsung', 'Galaxy S23', 'HANDY'),
('Samsung', 'Galaxy S23+', 'HANDY'),
('Samsung', 'Galaxy S23 Ultra', 'HANDY'),
('Samsung', 'Galaxy S23 FE', 'HANDY'),
('Samsung', 'Galaxy S24', 'HANDY'),
('Samsung', 'Galaxy S24+', 'HANDY'),
('Samsung', 'Galaxy S24 Ultra', 'HANDY'),
-- Samsung Galaxy A Series
('Samsung', 'Galaxy A13', 'HANDY'),
('Samsung', 'Galaxy A14', 'HANDY'),
('Samsung', 'Galaxy A23', 'HANDY'),
('Samsung', 'Galaxy A24', 'HANDY'),
('Samsung', 'Galaxy A33 5G', 'HANDY'),
('Samsung', 'Galaxy A34 5G', 'HANDY'),
('Samsung', 'Galaxy A52', 'HANDY'),
('Samsung', 'Galaxy A52s 5G', 'HANDY'),
('Samsung', 'Galaxy A53 5G', 'HANDY'),
('Samsung', 'Galaxy A54 5G', 'HANDY'),
('Samsung', 'Galaxy A55 5G', 'HANDY'),
('Samsung', 'Galaxy A71', 'HANDY'),
('Samsung', 'Galaxy A72', 'HANDY'),
('Samsung', 'Galaxy A73 5G', 'HANDY'),
-- Samsung Galaxy Note Series
('Samsung', 'Galaxy Note 8', 'HANDY'),
('Samsung', 'Galaxy Note 9', 'HANDY'),
('Samsung', 'Galaxy Note 10', 'HANDY'),
('Samsung', 'Galaxy Note 10+', 'HANDY'),
('Samsung', 'Galaxy Note 20', 'HANDY'),
('Samsung', 'Galaxy Note 20 Ultra', 'HANDY'),
-- Samsung Galaxy Z Fold/Flip
('Samsung', 'Galaxy Z Fold 3', 'HANDY'),
('Samsung', 'Galaxy Z Fold 4', 'HANDY'),
('Samsung', 'Galaxy Z Fold 5', 'HANDY'),
('Samsung', 'Galaxy Z Flip 3', 'HANDY'),
('Samsung', 'Galaxy Z Flip 4', 'HANDY'),
('Samsung', 'Galaxy Z Flip 5', 'HANDY'),
-- Xiaomi
('Xiaomi', 'Redmi Note 10', 'HANDY'),
('Xiaomi', 'Redmi Note 10 Pro', 'HANDY'),
('Xiaomi', 'Redmi Note 11', 'HANDY'),
('Xiaomi', 'Redmi Note 11 Pro', 'HANDY'),
('Xiaomi', 'Redmi Note 12', 'HANDY'),
('Xiaomi', 'Redmi Note 12 Pro', 'HANDY'),
('Xiaomi', 'Redmi Note 12 Pro+', 'HANDY'),
('Xiaomi', 'Redmi Note 13', 'HANDY'),
('Xiaomi', 'Redmi Note 13 Pro', 'HANDY'),
('Xiaomi', 'Redmi Note 13 Pro+', 'HANDY'),
('Xiaomi', 'Mi 11', 'HANDY'),
('Xiaomi', 'Mi 11 Lite', 'HANDY'),
('Xiaomi', 'Mi 11 Pro', 'HANDY'),
('Xiaomi', 'Mi 11 Ultra', 'HANDY'),
('Xiaomi', '12', 'HANDY'),
('Xiaomi', '12 Pro', 'HANDY'),
('Xiaomi', '12T', 'HANDY'),
('Xiaomi', '12T Pro', 'HANDY'),
('Xiaomi', '13', 'HANDY'),
('Xiaomi', '13 Pro', 'HANDY'),
('Xiaomi', '13T', 'HANDY'),
('Xiaomi', '13T Pro', 'HANDY'),
('Xiaomi', '14', 'HANDY'),
('Xiaomi', '14 Pro', 'HANDY'),
('Xiaomi', 'Poco F3', 'HANDY'),
('Xiaomi', 'Poco F4', 'HANDY'),
('Xiaomi', 'Poco F5', 'HANDY'),
('Xiaomi', 'Poco X3 Pro', 'HANDY'),
('Xiaomi', 'Poco X4 Pro', 'HANDY'),
('Xiaomi', 'Poco X5 Pro', 'HANDY'),
-- Huawei
('Huawei', 'P20', 'HANDY'),
('Huawei', 'P20 Pro', 'HANDY'),
('Huawei', 'P30', 'HANDY'),
('Huawei', 'P30 Pro', 'HANDY'),
('Huawei', 'P40', 'HANDY'),
('Huawei', 'P40 Pro', 'HANDY'),
('Huawei', 'P50', 'HANDY'),
('Huawei', 'P50 Pro', 'HANDY'),
('Huawei', 'P60', 'HANDY'),
('Huawei', 'P60 Pro', 'HANDY'),
('Huawei', 'Mate 20', 'HANDY'),
('Huawei', 'Mate 20 Pro', 'HANDY'),
('Huawei', 'Mate 30', 'HANDY'),
('Huawei', 'Mate 30 Pro', 'HANDY'),
('Huawei', 'Mate 40', 'HANDY'),
('Huawei', 'Mate 40 Pro', 'HANDY'),
('Huawei', 'Nova 9', 'HANDY'),
('Huawei', 'Nova 10', 'HANDY'),
('Huawei', 'Nova 11', 'HANDY'),
-- Sony Xperia
('Sony', 'Xperia 1', 'HANDY'),
('Sony', 'Xperia 1 II', 'HANDY'),
('Sony', 'Xperia 1 III', 'HANDY'),
('Sony', 'Xperia 1 IV', 'HANDY'),
('Sony', 'Xperia 1 V', 'HANDY'),
('Sony', 'Xperia 5', 'HANDY'),
('Sony', 'Xperia 5 II', 'HANDY'),
('Sony', 'Xperia 5 III', 'HANDY'),
('Sony', 'Xperia 5 IV', 'HANDY'),
('Sony', 'Xperia 5 V', 'HANDY'),
('Sony', 'Xperia 10 II', 'HANDY'),
('Sony', 'Xperia 10 III', 'HANDY'),
('Sony', 'Xperia 10 IV', 'HANDY'),
('Sony', 'Xperia 10 V', 'HANDY'),
-- Motorola
('Motorola', 'Moto G7', 'HANDY'),
('Motorola', 'Moto G8', 'HANDY'),
('Motorola', 'Moto G9', 'HANDY'),
('Motorola', 'Moto G10', 'HANDY'),
('Motorola', 'Moto G20', 'HANDY'),
('Motorola', 'Moto G30', 'HANDY'),
('Motorola', 'Moto G41', 'HANDY'),
('Motorola', 'Moto G51 5G', 'HANDY'),
('Motorola', 'Moto G52', 'HANDY'),
('Motorola', 'Moto G53 5G', 'HANDY'),
('Motorola', 'Moto G54 5G', 'HANDY'),
('Motorola', 'Moto G71 5G', 'HANDY'),
('Motorola', 'Moto G72', 'HANDY'),
('Motorola', 'Moto G73 5G', 'HANDY'),
('Motorola', 'Moto G84 5G', 'HANDY'),
('Motorola', 'Moto G Power', 'HANDY'),
('Motorola', 'Moto G Stylus', 'HANDY'),
('Motorola', 'Edge 20', 'HANDY'),
('Motorola', 'Edge 30', 'HANDY'),
('Motorola', 'Edge 30 Pro', 'HANDY'),
('Motorola', 'Edge 40', 'HANDY'),
('Motorola', 'Edge 40 Pro', 'HANDY'),
('Motorola', 'Razr 40', 'HANDY'),
('Motorola', 'Razr 40 Ultra', 'HANDY'),
-- Google Pixel
('Google', 'Pixel 4', 'HANDY'),
('Google', 'Pixel 4 XL', 'HANDY'),
('Google', 'Pixel 4a', 'HANDY'),
('Google', 'Pixel 5', 'HANDY'),
('Google', 'Pixel 5a', 'HANDY'),
('Google', 'Pixel 6', 'HANDY'),
('Google', 'Pixel 6 Pro', 'HANDY'),
('Google', 'Pixel 6a', 'HANDY'),
('Google', 'Pixel 7', 'HANDY'),
('Google', 'Pixel 7 Pro', 'HANDY'),
('Google', 'Pixel 7a', 'HANDY'),
('Google', 'Pixel 8', 'HANDY'),
('Google', 'Pixel 8 Pro', 'HANDY'),
('Google', 'Pixel 8a', 'HANDY'),
('Google', 'Pixel 9', 'HANDY'),
('Google', 'Pixel 9 Pro', 'HANDY'),
-- OnePlus
('OnePlus', 'Nord', 'HANDY'),
('OnePlus', 'Nord 2', 'HANDY'),
('OnePlus', 'Nord 3', 'HANDY'),
('OnePlus', 'Nord CE', 'HANDY'),
('OnePlus', 'Nord CE 2', 'HANDY'),
('OnePlus', 'Nord CE 3', 'HANDY'),
('OnePlus', '8', 'HANDY'),
('OnePlus', '8 Pro', 'HANDY'),
('OnePlus', '8T', 'HANDY'),
('OnePlus', '9', 'HANDY'),
('OnePlus', '9 Pro', 'HANDY'),
('OnePlus', '10 Pro', 'HANDY'),
('OnePlus', '11', 'HANDY'),
('OnePlus', '12', 'HANDY');