-- Add realme smartphone models to device_catalog with proper sorting
INSERT INTO public.device_catalog (device_type, brand, model, sort_order) VALUES
-- realme Number Series (newest first)
('HANDY', 'realme', 'realme 14 Pro+', 10),
('HANDY', 'realme', 'realme 14 Pro', 11),
('HANDY', 'realme', 'realme 14', 12),
('HANDY', 'realme', 'realme 13 Pro+', 20),
('HANDY', 'realme', 'realme 13 Pro', 21),
('HANDY', 'realme', 'realme 13', 22),
('HANDY', 'realme', 'realme 12 Pro+', 30),
('HANDY', 'realme', 'realme 12 Pro', 31),
('HANDY', 'realme', 'realme 12', 32),
('HANDY', 'realme', 'realme 12 5G', 33),
('HANDY', 'realme', 'realme 11 Pro+', 40),
('HANDY', 'realme', 'realme 11 Pro', 41),
('HANDY', 'realme', 'realme 11', 42),
('HANDY', 'realme', 'realme 11 5G', 43),
('HANDY', 'realme', 'realme 10 Pro+', 50),
('HANDY', 'realme', 'realme 10 Pro', 51),
('HANDY', 'realme', 'realme 10', 52),
('HANDY', 'realme', 'realme 9 Pro+', 60),
('HANDY', 'realme', 'realme 9 Pro', 61),
('HANDY', 'realme', 'realme 9', 62),
('HANDY', 'realme', 'realme 8 Pro', 70),
('HANDY', 'realme', 'realme 8', 71),
-- realme GT Series
('HANDY', 'realme', 'realme GT 6', 100),
('HANDY', 'realme', 'realme GT 5 Pro', 101),
('HANDY', 'realme', 'realme GT 5', 102),
('HANDY', 'realme', 'realme GT Neo 5', 110),
('HANDY', 'realme', 'realme GT Neo 3T', 111),
('HANDY', 'realme', 'realme GT Neo 3', 112),
('HANDY', 'realme', 'realme GT Neo 2', 113),
('HANDY', 'realme', 'realme GT Neo', 114),
('HANDY', 'realme', 'realme GT Master Edition', 120),
('HANDY', 'realme', 'realme GT 2 Pro', 121),
('HANDY', 'realme', 'realme GT 2', 122),
('HANDY', 'realme', 'realme GT', 123),
-- realme C Series
('HANDY', 'realme', 'realme C75', 200),
('HANDY', 'realme', 'realme C67', 201),
('HANDY', 'realme', 'realme C65', 202),
('HANDY', 'realme', 'realme C63', 203),
('HANDY', 'realme', 'realme C61', 204),
('HANDY', 'realme', 'realme C55', 210),
('HANDY', 'realme', 'realme C53', 211),
('HANDY', 'realme', 'realme C51', 212),
('HANDY', 'realme', 'realme C35', 220),
('HANDY', 'realme', 'realme C33', 221),
('HANDY', 'realme', 'realme C31', 222),
('HANDY', 'realme', 'realme C30', 223),
('HANDY', 'realme', 'realme C25Y', 230),
('HANDY', 'realme', 'realme C25', 231),
('HANDY', 'realme', 'realme C21Y', 232),
('HANDY', 'realme', 'realme C21', 233),
-- realme Narzo Series
('HANDY', 'realme', 'realme Narzo 70 Pro', 300),
('HANDY', 'realme', 'realme Narzo 70', 301),
('HANDY', 'realme', 'realme Narzo 60 Pro', 310),
('HANDY', 'realme', 'realme Narzo 60', 311),
('HANDY', 'realme', 'realme Narzo 50 Pro', 320),
('HANDY', 'realme', 'realme Narzo 50', 321)
ON CONFLICT DO NOTHING;